version: '3'
services:
  db:
    image: postgres:10.3
    environment:
      POSTGRES_PASSWORD: 'randyforcongress'
  web:
    build: .
    command: >
      bash -c "python3 manage.py collectstatic --noinput;
      python3 manage.py createdb --noinput;
      python3 manage.py migrate;
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
